language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t nicolasnunez96/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nicolasnunez96/docker-react npm run test
